spring.application.name=report-service

server.port=8090

# Importar secretos (solo local). En Docker se usan variables de entorno.
spring.config.import=optional:file:./secrets.properties

# URLs de los microservicios que consulta Reportes
sales.service.url=http://${DB_HOST:localhost}:8085
catalog.service.url=http://${DB_HOST:localhost}:8084
agenda.service.url=http://${DB_HOST:localhost}:8081

# JWT - El secret DEBE ser el mismo del servicio de Auth
jwt.secret=${JWT_SECRET}
jwt.expiration=360000

# SWAGGER / OPEN API
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# ---- EUREKA (Service Discovery) ----
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
