spring.application.name=reportes
server.port=8088

# URLs de los microservicios que consulta Reportes
sales.service.url=http://localhost:8085
catalog.service.url=http://localhost:8084
agenda.service.url=http://localhost:8081

# JWT - El secret DEBE ser el mismo del servicio de Auth
jwt.secret=nirFGYRTKqzxHJlwfgmJb3Avh6cmQfPadj1qU1TbHEk
jwt.expiration=360000



